### ISSUE TITLE
NullReferenceException in PH_S032

### ISSUE THREAD

**Issue by hsrfvetsch** [Concurrency-Lab/ParallelHelper#106]
The following code results in NullReferenceException:

```cs
        internal Task<bool> DoSomethingAsync() {
            try {
            } catch(Exception) {
                throw;
            }
            return Task.FromResult(true);
        }
```

Stack Trace:
```
Analyzer 'ParallelHelper.Analyzer.Smells.ThrowsInPotentiallyAsyncMethodAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: node'.
Exception occurred with following context:
Compilation: ConsoleApp3
SyntaxTree: 
SyntaxNode: internal Task<bool> DoSomethingAsync ... [MethodDeclarationSyntax]@[74..260) (2,8)-(8,9)

System.ArgumentNullException: Value cannot be null.
Parameter name: node
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfoCore(SyntaxNode node, CancellationToken cancellationToken)
   at ParallelHelper.Analyzer.Smells.ThrowsInPotentiallyAsyncMethodAnalyzer.Analyzer.IsAnySubTypeOf(SyntaxNode node, IEnumerable`1 types)
   at ParallelHelper.Analyzer.Smells.ThrowsInPotentiallyAsyncMethodAnalyzer.Analyzer.IsThrowsWithoutExcludedType(SyntaxNode node, IEnumerable`1 excludedBaseTypes)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at ParallelHelper.Analyzer.Smells.ThrowsInPotentiallyAsyncMethodAnalyzer.Analyzer.Analyze()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: PH_S032

```

**Comment by camrein** [comment]
Sorry for the delay. I've just fixed the issue, thanks for reporting!
